# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.3.4
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: Travis
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
rebel_module_groups: []
repo_description: This project aim to deal with modules related to manage carriers
  and deliveries in a generic way.
repo_name: Carriers And Deliveries Management
repo_slug: delivery-carrier
travis_apt_packages: []
travis_apt_sources: []
