{
    "name": "DHL Germany Shipping",
    "summary": "Print DHL DE shipping labels",
    "version": "13.0.1.0.0",
    "author": "brain-tec AG, Odoo Community Association (OCA)",
    "maintainer": "brain-tec AG",
    "license": "AGPL-3",
    "category": "Delivery",
    "complexity": "normal",
    "depends": ["delivery", "mail", "base"],
    "website": "http://www.braintec-group.com",
    "data": [
        "views/delivery_carrier.xml",
        "views/stock_picking_views.xml",
        "views/view_res_partner.xml",
    ],
    "external_dependencies": {"python": ["zeep", "defusedxml"]},
    "installable": True,
    "auto_install": False,
    "application": True,
}
