<definitions name="createShipmentOrder"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             targetNamespace="http://dhl.de/webservices/businesscustomershipping/3.0"
             xmlns:cis="http://dhl.de/webservice/cisbase"
             >
  <types>
      <xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified">
          <xsd:import namespace="http://dhl.de/webservice/cisbase" schemaLocation="cis_namespace.xsd"/>
        <xsd:import namespace="http://dhl.de/webservices/businesscustomershipping/3.0" schemaLocation="createShipmentOrder-val-global-req-6.2.xsd"/>

      </xsd:schema>
  </types>
</definitions>
